### ISSUE TITLE
Error when using opensc-pkcs11 library

### ISSUE THREAD

**Issue by netmiller** [PeculiarVentures/graphene#103]
I'm trying to make signature with my Yubikey4 + graphene + OpenSC-library (opensc-pkcs11.so)
But got an error __Error: CKR_USER_NOT_LOGGED_IN:257__ 

Exactly same code is working fine when using Yubico:s lib 'libykcs11.dylib', but I want to use opensc as 'run-time-lib'.  Some discussions with pkcs11interop-site are tipping : 

> ykcs11 should be used only to generate keys with Yubikey-specific attributes. For everything else - opensc-pkcs11.

and I have also experiences where Yubico's lib/libs are quite mess when using Windows-environment (.dll's).

So I tried to tackle this with using Opensc:n lib, because I need this with my windows-version (mandatory with my customers).  I guess if I get it working with OSX, it have good chance to solve this also in windows-ebcironment.

My code is a little bit verbose because of other functionality, but here is some relevant points.
I can generate a short version to produce same error, if it helps ?

````
const graphene = require("graphene-pk11");
const Module = graphene.Module;
// const lib = './lib/libykcs11.dylib';     // works like charm
const lib = './lib/opensc-pkcs11.so';       // gives Error: CKR_USER_NOT_LOGGED_IN:257
. . . . 
session.login("123456", graphene.UserType.USER);     // login works well
. . . .
// this is throwin error when using opensc, but works with yubico's lib
let signature = session.createSign("SHA256_RSA_PKCS", privKey).once(JSON.stringify(payload.meta));

````

Any idea is this related to my code or some bug with graphene or something else ??

**Comment by microshine** [comment]
@netmiller You code looks good. Can you try get private key options. I'm interesting in `CKA_ALWAYS_AUTHENTICATE` attribute.

Can be useful https://github.com/OpenSC/OpenSC/issues/1039

**Comment by netmiller** [comment]
Yes, ALWAYS_AUTHENTICATE is one thing I found which may cause this. 
But can't figure where to set/get this in Graphene-workflow ? Any help, and I will try.

**Comment by netmiller** [comment]
Maybe I've got it working by adding extra login after SignInit (session.createSign).

I changed my code this way :

````
 // do not use createSign.once 
// const signature = session.createSign("ECDSA_SHA256", privKey).once(JSON.stringify(payload.meta));

// instead use "longer way"
    var sign2 = session.createSign("SHA256_RSA_PKCS", privKey);
    session.login("776655", graphene.UserType.CONTEXT_SPECIFIC);
    sign2.update(JSON.stringify(payload.meta));
    var signature = sign2.final();
````

Here I make "another login" with UserType.CONTEXT_SPECIFIC (after SignInit), and now it works (at least returns reasonable signature).

I'm not sure if it is right solution, so give me better ideas if not.

Also noticed from Yubikey's piv-tool help :

````
  9a is for PIV Authentication
  9c is for Digital Signature (PIN always checked)
````
I will try to test using slot 9a also for signing ; just to see if it works differently.

**Comment by netmiller** [comment]
Seems to work  when using slot 9a .  I can still make signature (with or without extra "session.login(...)" .  This case I have deleted slot 9c.

````
    var sign2 = session.createSign("SHA256_RSA_PKCS", privKey);
    // session.login("123456", graphene.UserType.CONTEXT_SPECIFIC); 
    sign2.update(JSON.stringify(payload.meta));
    var signature = sign2.final();
````
 when using slot 9c I have to take in effect "session.login(...)"  ; otherwise  : 
Error: CKR_USER_NOT_LOGGED_IN:257
