### ISSUE TITLE
How to use usb token pkcs#11 certificate for Nodejs https client?

### ISSUE THREAD

**Issue by doganmurat** [PeculiarVentures/graphene#105]
If you have a client certificate pair (self signed) then you can make a https get call like this in nodejs;

request.get({
      url: 'https://example.com/list',
      key: certificate.key,
      cert: certificate.cert,
      ca: certificate.ca
    }, (error, response, body) => {
      ...
    });
How will we write this code if we are storing certificate pair in a hardware PKI token like ePass2003?

Could graphene has a solution for that?

Will we read key & cert from PKI token? or

Will we use another method?

Please note that, in this scenario all clients must have a valid certificate in order to connect server.

Thanks,

**Comment by microshine** [comment]
As I can see from NodeJS API `cert` and `key` must be in PEM fromat. So you need to export these objects from token and encode them to PEM format. But it's not possible if private key is not extractable.

You can use [node-webcrypto-p11](https://www.npmjs.com/package/node-webcrypto-p11) package which allows to export keys in PKCS8/SPKI formats. Then you can use `PemConverter` class from [webcrypto-core](https://github.com/PeculiarVentures/webcrypto-core) package (it's a dependence of `node-webcrypto-p11`) to convert blobs to PEM ([example](https://github.com/PeculiarVentures/webcrypto-core/blob/master/test/pem_converter.ts#L24))

**Comment by doganmurat** [comment]
Hi @microshine ,

Thank you for response.
Normally private key is not extractable.

I guess I need a different approach, but could not find a way yet.

There is a sample code at [stackoverflow](https://stackoverflow.com/questions/23525241/how-to-access-a-url-that-requires-a-safenet-etoken-certificate-using-java) for java .
I didn't try the code but seems logical.
They are creating a custom ssl socket.

**Comment by microshine** [comment]
I'm not sure that it's possible to customize Cert auth in NodeJs API

**Comment by rmhrisk** [comment]
It is not, you might be able to get this to work via OpenSSL engine. Good luck.
