### ISSUE TITLE
How I init a RSA keypair given a value?

### ISSUE THREAD

**Issue by Tusabras** [PeculiarVentures/graphene#108]
For example I want to init my HSM RSA key pairs given:

-----BEGIN RSA PRIVATE KEY-----
IEtgmyDq2G3K9EJKZWBbd......
-----END RSA PRIVATE KEY-----

-----BEGIN RSA PUBLIC KEY-----
/6Qt6qPOXMpcAJzwE0N19......
-----END RSA PUBLIC KEY-----

How can be done? Generating the RSA giving the modulus and public exponential?

**Comment by rmhrisk** [comment]
Are you asking how to import a key?

**Comment by microshine** [comment]
I would like to suggest you using [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11) module. It's based on `graphene` and simplifies key and certificate working.

You can use:
- crypto.subtle [importKey/exportKey](https://github.com/PeculiarVentures/webcrypto-docs/blob/master/RSA_SSA.md#rsassa-pkcs1-v1_5) operations to import/export key in JWK/SPKI/PKCS8 formats
- [crypto.keyStorage.setItem](https://github.com/PeculiarVentures/webcrypto-docs/blob/master/CRYPTO_STORAGE.md#CryptoStorage-interface) to add imported key to token

**Comment by microshine** [comment]
If you want to do it by `graphene` you need to use ASN.1 parser and do it like [here](https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/mechs/rsa/crypto.ts#L86-L112)

**Comment by Tusabras** [comment]
Ye i was checking the node-webcrypto-p11 module, but the message on the
README that it might not be ready for production environments might not be
ready yet... How secure it is to create production things using
node-webcrypto-p11 module?

**Comment by rmhrisk** [comment]
Several production applications use that library. We have simply not hired a external party to review it yet.

**Comment by Tusabras** [comment]
cool! ye was able to do it at the end, thank you! for the help:)
