### ISSUE TITLE
AES_GCM support for SoftHSM

### ISSUE THREAD

**Issue by jonasholtkamp** [PeculiarVentures/graphene#112]
Graphene's [list of capabilities](https://github.com/PeculiarVentures/graphene/tree/master/capabilities) states that Graphene supports AES_GCM for devices other than SoftHSM. However, SoftHSM supports AES_GCM for about two years now ([see PR here](https://github.com/opendnssec/SoftHSMv2/pull/344)). If I use Graphene with SoftHSM and use AES_GCM as my cipher I get the following error: ` Error: CKR_MECHANISM_INVALID:112`

**Comment by rmhrisk** [comment]
CKR_MECHANISM_INVALID Is a return from SoftHSM. This suggests they do not support AES_GCM via the same way that the  HSMs we tested against (Safenet, Thales, etc).

Do you have a link to documentation and/or an example of how to use SoftHSM with AES_GCM?

Are you sure your running the most recent SoftHSM?

**Comment by microshine** [comment]
### AES GCM encryption
```ts
import * as graphene from "graphene-pk11";

async function main() {
  const softHsm = graphene.Module.load("/usr/local/lib/softhsm/libsofthsm2.so");

  softHsm.initialize();

  try {
    const slot = softHsm.getSlots(0);
    const mechs = slot.getMechanisms();

    //#region Check AES_GCM algorithm
    let aesGcm: graphene.Mechanism | null = null;
    for (let i = 0; i < mechs.length; i++) {
      const mech = mechs.items(i);
      if (mech.name === "AES_GCM") {
        aesGcm = mech;
      }
    }

    console.log("SoftHSM version:", `v${softHsm.libraryVersion.major}.${softHsm.libraryVersion.minor}`)

    if (!aesGcm) {
      throw new Error("AES GCM mechanism is not supported");
    }
    //#endregion

    const session = slot.open(graphene.SessionFlag.SERIAL_SESSION);
    session.login("12345");

    //#region Generate AES key
    const key = session.generateKey(
      graphene.KeyGenMechanism.AES,
      {
        class: graphene.ObjectClass.SECRET_KEY,
        token: false,
        valueLen: 16,
        encrypt: true,
        decrypt: true,
      },
    );
    //#endregion

    //#region Encrypt message using AES GCM mechanism
    const cipher = session.createCipher(
      {
        name: "AES_GCM",
        params: new graphene.AesGcm240Params(Buffer.from("123456789012"))
      },
      key,
    );

    const enc = cipher.once(Buffer.from("Message to encrypt"), Buffer.alloc(128));
    console.log("Encrypted message:", enc.toString("hex"));
    //#endregion
  }
  catch (e) {
    softHsm.finalize();
    throw e;
  }
}

main()
  .catch((err) => {
    console.log(err);
  });
```

### Output
```
SoftHSM version: v2.5
Encrypted message: 1c1fc5e4db40711dc1b92ae1a7565a97a727151892124e542d66517e7a18b754ca3b
```

**Comment by rmhrisk** [comment]
@microshine does that mean it works for you with latest version of softhsm?

**Comment by microshine** [comment]
Yes, it does. Maybe @jonasholtkamp uses SoftHSM with disabled AEG GCM mechanism

https://github.com/opendnssec/SoftHSMv2/blob/develop/src/lib/SoftHSM.cpp#L2222-L2246

**Comment by rmhrisk** [comment]
OK closing as resolved.

**Comment by jonasholtkamp** [comment]
I'm using SoftHSM version 2.4 which by [the changelog supports GCM](https://github.com/opendnssec/SoftHSMv2/blob/master/NEWS#L41). I do know now that this probably isn't an issue with Graphene. However maybe someone can point me to some bits of information/documentation anyhow.

@microshine: You surely did import an AES key first? If so, how?

Sorry for re-opening the already closed issue.

**Comment by microshine** [comment]
### Generate AES-128 key
```ts
const key = session.generateKey(
  graphene.KeyGenMechanism.AES,
  {
    class: graphene.ObjectClass.SECRET_KEY,
    token: false,
    valueLen: 16,
    encrypt: true,
    decrypt: true,
  },
);
```

### Import AES-128 key
```ts
const key = session.create(
  {
    class: graphene.ObjectClass.SECRET_KEY,
    keyType: graphene.KeyType.AES,
    token: false,
    value: Buffer.from("1234567890abcdef"),
    encrypt: true,
    decrypt: true,
  },
).toType();
```
