### ISSUE TITLE
unknown Mechanisms

### ISSUE THREAD

**Issue by anubnair** [PeculiarVentures/graphene#117]
I am trying to print all mechanisms and i am getting lots of unknown Mechanisms

Mechanisms:
Name                       h/s/v/e/d/w/u
========================================
RSA_PKCS_KEY_PAIR_GEN      -/-/-/-/-/-/-
RSA_PKCS                   -/+/+/+/+/+/+
unknown                    -/-/-/+/+/-/-
unknown                    -/-/-/-/-/-/-
unknown                    -/-/-/-/-/-/-
unknown                    -/-/-/-/-/-/-

**Comment by rmhrisk** [comment]
It is common for HSMs to implement proprietary mechanisms. These will show as unknown as they are not defined in the PKCS11 RFC?

**Comment by microshine** [comment]
@alexgbv Use [vendor](https://github.com/PeculiarVentures/graphene/blob/master/index.d.ts#L1141-L1143) function to register new mechanisms in graphene

```js
Mechanism.vendor("BIP32_MASTER_DERIVE", 0x80000001);
```
