### ISSUE TITLE
Support secp256k1 

### ISSUE THREAD

**Issue by wshbair** [PeculiarVentures/graphene#126]
It possible to support the secp256k1 beside secp256r1 ? I see the first version support it but in the later versions it is not existed

**Comment by rmhrisk** [comment]
Yes but tits dependent on it and how your HSM supports it since PKCS11 doesn’t specify how this works.

See: https://github.com/PeculiarVentures/graphene/issues/123

**Comment by wshbair** [comment]
> HSM

Sorry, I didn't get your question. I am quite new in this field. I am exploring the SoftHSMv2 for development and then shift to AWS CloudHSM which supports the secp256k1

**Comment by microshine** [comment]
Fixed in a new version `graphene-pk11@2.1.6`
https://github.com/PeculiarVentures/graphene/blob/master/src/keys/ec/curves.ts#L5
