### ISSUE TITLE
How to extract public key from ECDSA (secp256k1)

### ISSUE THREAD

**Issue by wshbair** [PeculiarVentures/graphene#127]
An [stackoverflow](https://stackoverflow.com/questions/55832827/why-does-the-same-hsm-key-verify-to-a-different-ethereum-address-every-time) said to extract the public key we need to " _pull out the public key using its "pointEC" attribute:_ " is it true ?

**Comment by rmhrisk** [comment]
Not sure I understand.

it is possible to derive the public key of a given private key with secp256k1 - https://bitcoin.stackexchange.com/questions/25024/how-do-you-get-a-bitcoin-public-key-from-a-private-key

But your implementation may also just set CKO_PUBLIC_KEY containing the corresponding public key.

**Comment by microshine** [comment]
@wshbair If you need to export EC public key from PKCS#11 object use `pointEC`

[node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11) is based on `graphene-pk11` implements WebCrypto interface and allows to export EC keys in `PKCS8`, `SPKI` and `JWK` formats.

https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/mechs/ec/crypto.ts#L192

**Comment by wshbair** [comment]
@microshine @rmhrisk Thanks for answering my question, 
Yes, it seems true to use the pointEC, however it includes uncompressed public key. Based on some expirments with SoftHSMv2 the pointEC length is 67 Bytes, so to get valid key I need to remove the first 3 bytes (keys.publicKey.getAttribute({pointEC: null}).pointEC.slice(3,67)). 

This approach has been tested to generate Ethereum address and the recovred the public key from signed messages.

**Comment by microshine** [comment]
Source code from `node-webcrypto-p11` for uncompressed EC point decoding
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/mechs/ec/utils.ts#L36-L49

**Comment by wshbair** [comment]
I integrated the EC point decoding function . It assumes the public key is 65 Byte, which it MUST be accoring to [RFC5480](https://tools.ietf.org/html/rfc5480#section-2.2). The first byte is "04" of uncompressed key. So by the given function we remove the first Byte. 
 
In my case, the retrun key is 67 bytes where it always start with "044104", so I need to remove the first 3 bytes to make it works. it may be a bug ?

**Comment by microshine** [comment]
It's ASN encoded value
`04` - `OCTET STRING`
`41` - Length 65 bytes

![image](https://user-images.githubusercontent.com/7333669/76548241-7db7da00-649f-11ea-818b-3660ce2a9abb.png)

For `secp256k1` curve it's always `044104` at the beginning

**Comment by wshbair** [comment]
@microshine that makes sense, thanks for support!
