### ISSUE TITLE
Is there a way to detect HW changes (slots/tokens)?

### ISSUE THREAD

**Issue by heol-files** [PeculiarVentures/graphene#129]
Is there a way to get events (promises) on slot and token changes in graphene?
* Card reader connect/disconnect
* Card insert/removal
* Yubikey (I guess it's both above sequentially)

Or, do you have any recommendations on how to solve the above?

**Comment by microshine** [comment]
[pcsclite](https://www.npmjs.com/package/pcsclite) allows to get those events

**Comment by abdalahshaban** [comment]
@heol-files you can use usb-detection package 
https://www.npmjs.com/package/usb-detection

**Comment by rmhrisk** [comment]
Not all cards/tokens are USB based; the higher level pc/sc would work for both cases.
