### ISSUE TITLE
Create constants for session start options

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/graphene#13]
Right now there are magic numbers that are ored together for specifing read-write mode:

```
        session.start(2 | 4); //start session in RW mode
```

For a session, we should make sure there is a enum/constants for these values and get samples updated to use them.

**Comment by microshine** [comment]
There is enum for session start
```
SessionFlags{
		/**
		* session is r/w
		*/
		ReadWrite: number;
		/**
		* no parallel 
		*/
		Serial: number;
}
```
