### ISSUE TITLE
How to fix it [ lib.load(libFile) ]

### ISSUE THREAD

**Issue by amitraky** [PeculiarVentures/graphene#134]
Hi,
when I m loading the `SignatureP11.dll` file 

```\node_modules\graphene-pk11\build\cjs\module.js:16
        lib.load(libFile);
            ^

Error: Win32 error 126
    at Error (native) PKCS11::Load:136
```

So how we can fix it

**Comment by rmhrisk** [comment]
Without more detail and the library to reproduce the issue it’s really impossible to say but my guesses are:

- 32bit lib vs 64bit runtime 
- ACLs on the library
- corrupt library

**Comment by amitraky** [comment]
Yes it's  (32bit lib vs 64bit runtime)
