### ISSUE TITLE
how can add data on token 

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/graphene#137]
how can add data on token and how get it again to use it in some checkes

**Comment by microshine** [comment]
What kind of data do you mean? PKCS#11 supports `CKO_DATA`, `CKO_CERTIFICATE`, `CKO_PUBLIC_KEY`, `CKO_PRIVATE_KEY`, `CKO_SECRET_KEY`, `CKO_HW_FEATURE`, `CKO_DOMAIN_PARAMETERS`, and `CKO_MECHANISM`

**Comment by abdalahshaban** [comment]
i need to add flag or random number in token and get it again to make condition

**Comment by abdalahshaban** [comment]
i found  graphene.Storage how can use it

**Comment by abdalahshaban** [comment]
> CKO_DATA

CKO_DATA

**Comment by microshine** [comment]
Use [Session.create](https://peculiarventures.github.io/graphene/classes/session.html#create) method. See [object creation](https://github.com/PeculiarVentures/graphene/blob/master/test/object.ts#L156-L162) test

**Comment by abdalahshaban** [comment]
what about Storage.set() ?
