### ISSUE TITLE
how can get ID of PKCS#11 object to use in Storage

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/graphene#138]
how can get ID of PKCS#11 object to use in Storage

**Comment by microshine** [comment]
1. Use [SessionObject.getAttribute](https://peculiarventures.github.io/graphene/classes/sessionobject.html#getattribute)
```js
console.log(sessionObject.getAttribute("id"));
```
2. Convert SessionObject to Data and use `id` property
```js
const data = sessionObject.toType();
console.log(data.id);
```

**Comment by abdalahshaban** [comment]
Cannot read property 'C_GetAttributeValue' of undefined
