### ISSUE TITLE
how can solve user pin  has been blocked

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/graphene#139]

**Comment by abdalahshaban** [comment]
CKR_PIN_LOCKED

**Comment by microshine** [comment]
I'm not sure you can do it using PKCS#11 functions. You need to use your token tools

**Comment by abdalahshaban** [comment]
can recommend any token tools to do this

**Comment by rmhrisk** [comment]
You should be able to use plcs11-tool if support for your specific card was added, alternatively you can use the smart card middleware but regardless you can unlock it without the PUK.

**Comment by abdalahshaban** [comment]
number of SO pin ?

**Comment by rmhrisk** [comment]
Not all Smart Cards support the Change SO PIN function. Some cards are don't have SO PINs, but instead use challenge/response processes with a PUK.

Each card type is different and what the values are is dependent on how they were provisioned.

SO is Security Operator; essentially card admin.

PUK is a Unblock Pin: it is used as a one time reset code or used with a challenge response process to unblock the card.
