### ISSUE TITLE
message: "Win32 error 126" 

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/graphene#140]
load ok when run in dev mod.
but throw error{
 message: "Win32 error 126"
method: "Load"
name: "NativeError"
nativeStack: "    at Error (native) PKCS11::Load:135
"}
when build it and use app.exe

**Comment by microshine** [comment]
Please doublecheck path to PKCS#11 library. Looks like your application uses the wrong path.
```
ERROR_MOD_NOT_FOUND

126 (0x7E)

The specified module could not be found
```

**Comment by abdalahshaban** [comment]
i agree with you 
but if wrong path how work in dev mode electron .

but not work when wrap it with electron builder and generate app.exe and install it then not work like dev mode

**Comment by microshine** [comment]
Are you using the absolute path to PKCS#11 library?

**Comment by abdalahshaban** [comment]
let dllPath = path.join(__dirname, '../../../lib/eps2003csp11.dll')
 let mod = graphene.Module.load(dllPath)

**Comment by microshine** [comment]
Print `dllPath` variable. Looks like complied `app.exe` uses another value for `__dirname`

**Comment by abdalahshaban** [comment]
ok
dllpath change when build electron but i solved it
