### ISSUE TITLE
how can get Certificate details (valid from - to)

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/graphene#141]

**Comment by abdalahshaban** [comment]
const certificates = session.find({
      class: graphene.ObjectClass.CERTIFICATE,
    })

 if (cert instanceof graphene.X509Certificate) {
      console.log('Certificate info:\n===========================')
      console.log('startDate', cert.startDate)
      console.log('End Date', cert.endDate)
    }

**Comment by microshine** [comment]
Do you use `toType` function after `find`? It must convert session object to X509Certificate

**Comment by abdalahshaban** [comment]
const cert = certificates.items(0).toType()

**Comment by microshine** [comment]
![image](https://user-images.githubusercontent.com/7333669/104448596-6f9a8480-55ae-11eb-842a-8a5638eef961.png)

**Comment by abdalahshaban** [comment]
i see error when get startDate

**Comment by microshine** [comment]
looks like `graphene` should return null if `startDate` is empty.

**Comment by abdalahshaban** [comment]
why start Date Or end Date return null ?

**Comment by microshine** [comment]
You can set those values manually. Looks like they weren't set during certificate adding to the token.

Those attributes are for quick information getting (metadata). You can get that information by parsing DER encoded `value` which keeps the certificate blob
