### ISSUE TITLE
How to init a token with given user PIN (not SO PIN)

### ISSUE THREAD

**Issue by nghianinhnb** [PeculiarVentures/graphene#150]
First i init a token in the free slot with given PIN and Label:

> var slots = mod.getSlots(true);
> slots.items(slots.length-1).initToken('1234', 'BKC Lab 1')

And check it with softhsm-ultil: 
`sudo softhsm2-util --show-slots`

> Slot 1632399937
>     Slot info:
>         Description:      SoftHSM slot ID 0x614c7241                                      
>         Manufacturer ID:  SoftHSM project                 
>         Hardware version: 2.6
>         Firmware version: 2.6
>         Token present:    yes
>     Token info:
>         Manufacturer ID:  SoftHSM project                 
>         Model:            SoftHSM v2      
>         Hardware version: 2.6
>         Firmware version: 2.6
>         Serial number:    376960de614c7241
>         Initialized:      yes
>         User PIN init.:   no
>         Label:            BKC Lab 1

Then i try to init user PIN by:

> var slot, session;
> 
>   try {
>       slot = mod.getSlots(1);    // 1 is index of this slot
>       slot.closeAll();
>       session = slot.open();
>       session.initPin('12345');
> 
>   } catch(e) {
>       if (session) {
>           session.logout();
>           session.close();
>       }
>       console.log(e);
>   }

It say: 

> [Pkcs11Error: CKR_USER_NOT_LOGGED_IN] {
>   method: 'C_InitPIN',
>   nativeStack: '    at Error (native) C_InitPIN:354',
>   code: 257
> }

But when i login:

> var slot, session;
> 
> try {
>     slot = mod.getSlots(1);
>     slot.closeAll();
>     session = slot.open();
>     session.login('1234', graphene.UserType.SO);
>     session.initPin('12345');
> 
> } catch(e) {
>     if (session) {
>         session.logout();
>         session.close();
>     }
>     console.log(e);
> }

It say:

> [Pkcs11Error: CKR_SESSION_READ_ONLY_EXISTS] {
>   method: 'C_Login',
>   nativeStack: '    at Error (native) C_Login:432',
>   code: 183
> }

Can't do it with graphene.UserType.USER too:

> [Pkcs11Error: CKR_USER_PIN_NOT_INITIALIZED] {
>   method: 'C_Login',
>   nativeStack: '    at Error (native) C_Login:432',
>   code: 258
> }

@rmhrisk  @microshine

**Comment by rmhrisk** [comment]
You can’t initialize a token with a user pin with every card/token I’ve ever used.

**Comment by nghianinhnb** [comment]
but when i use 
`softhsm2-util --init-token --free --label text  --so-pin 1234 --pin 1234`
It work. How cant i mimic that because i need log user in token to create key pair

**Comment by microshine** [comment]
SoftHSM run `C_InitToken` for `--init-token` command. Looking through their implementation and trying to reproduce the same logic using the `graphene` module

**Comment by microshine** [comment]
Here is my example. It works fine with SoftHSM

**TypeScript**
```ts
import * as graphene from "graphene-pk11";

const soPin = "12345";
const userPin = "12345";
const label = "NodeJS slot initialized";

async function main() {
  const softhsm = graphene.Module.load("/usr/local/lib/softhsm/libsofthsm2.so");
  softhsm.initialize();
  try {
    const slots = softhsm.getSlots(true);
    for (const slot of slots) {
      let token = slot.getToken();
      if (token.flags & graphene.TokenFlag.TOKEN_INITIALIZED) {
        // console.log("Token is initialized");
      } else {
        console.log("Token is not initialized");

        // Init token
        slot.initToken(soPin, label);
        token = slot.getToken();
        console.log(`Token with serial number '${token.serialNumber}' has been created`);

        const session = slot.open(graphene.SessionFlag.RW_SESSION | graphene.SessionFlag.SERIAL_SESSION);
        session.login(soPin, graphene.UserType.SO);
        session.initPin(userPin);
        break;
      }
    }
  } finally {
    softhsm.finalize();
  }
}

main().catch(e => console.error(e));
```

**SoftHSM --show-slots**
```
> softhsm2-util --show-slots                                    
Available slots:
Slot 1320827174
    Slot info:
        Description:      SoftHSM slot ID 0x4eba3926                                      
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.6
        Firmware version: 2.6
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.6
        Firmware version: 2.6
        Serial number:    e6b114d84eba3926
        Initialized:      yes
        User PIN init.:   yes
        Label:            NodeJS slot initialized
```

**Comment by rmhrisk** [comment]
SoftHSM is designed as a testing platform for HSMs. Physical tokens are designed as a way to secure cryptographic keys. 

The security officer concept exists to provide administrative control over tokens.

Some tokens are read only tokens where they can only have key generation performed at initialization time while others will let you do it at run time. 

Those that let you do it at runtime allow keys to be generated by the user. 

Initialization always happens in real tokens as the admin, even if throwaway admin keys are used.

The protocols for initialization and necessary provisioning steps carry device to device, some require their propietary provisioning middleware to be used, some are integrated into larger card management platforms. 

There is no one size fits all solution to initialization and unblock.

Login, eygen, signing/verifying, encrypt/decrypt, pin change, logout - these work cross device reliably.

**Comment by nghianinhnb** [comment]
Thank you very much. You save my life. And do it work good with many request
