### ISSUE TITLE
How to install release 1.1.0  ?

### ISSUE THREAD

**Issue by ValeryEliseev** [PeculiarVentures/graphene#37]
When i wrote
npm install graphene-pk11
i received version 1.0.0 (without session.export method)

When i wrote 
npm install graphene-pk11@1.1.0
i got error
npm ERR! version not found: graphene-pk11@1.1.0

When i manually download graphene-1.1.0.zip and replace lib folder, i got javascript error:
Uncaught Error: Cannot find module 'base64url'

How properly install latest release?

**Comment by rmhrisk** [comment]
@ValeryEliseev we just are putting the finishing touches on 2.0, we re-wrote it in TypeScript. I expect it to be published as a module tomorrow. Feedback appriciated.

**Comment by microshine** [comment]
Hello! You can download new version of `graphene` from `npm`
```
npm install graphene
```
