### ISSUE TITLE
Add support for C_GetFunctionList

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/graphene#38]
It seems not all libraries export their functions by name, this is accommodated in PKCS#11 via the C_GetFunctionList API.

We need to re-tool Graphene to use this API to work with these implementations.

**Comment by rmhrisk** [comment]
The biggest question here is how to use the returns from C_GetFunctionList with FFI

**Comment by AndreaFrancis** [comment]
I've been trying to test graphene with opensc-pkcs11.so library,like this:
`/*var lib = "/usr/lib/softhsm/libsofthsm.so";*/
var graphene = require("graphene-pk11");
var lib = "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so";
var Module = graphene.Module;

var mod = Module.load(lib, "SoftHSM");
mod.initialize();
// get slots
var slots = mod.getSlots(true);
if (slots.length > 0) {
    for (var i = 0; i < slots.length; i++) {
        var slot = slots.items(i);
        console.log("Slot #" + slot.handle);
        console.log("\tDescription:", slot.slotDescription);
        console.log("\tSerial:", slot.getToken().serialNumber);
        console.log("\tPassword(min/max): %d/%d", slot.getToken().minPinLen, slot.getToken().maxPinLen);
        console.log("\tIs hardware:", !!(slot.flags & graphene.SlotFlag.HW_SLOT));
        console.log("\tIs removable:", !!(slot.flags & graphene.SlotFlag.REMOVABLE_DEVICE));
        console.log("\tIs initialized:", !!(slot.flags & graphene.SlotFlag.TOKEN_PRESENT));
        console.log("\n\nMechanisms:");
        console.log("Name                       h/s/v/e/d/w/u");
        console.log("========================================");
        function b(v) {
            return v ? "+" : "-";
        }
        ;
        function s(v) {
            v = v.toString();
            for (var i_1 = v.length; i_1 < 27; i_1++) {
                v += " ";
            }
            return v;
        }
        ;
        var mechs = slot.getMechanisms();
        for (var j = 0; j < mechs.length; j++) {
            var mech = mechs.items(j);
            console.log(s(mech.name) +
                b(mech.flags & graphene.MechanismFlag.DIGEST) + "/" +
                b(mech.flags & graphene.MechanismFlag.SIGN) + "/" +
                b(mech.flags & graphene.MechanismFlag.VERIFY) + "/" +
                b(mech.flags & graphene.MechanismFlag.ENCRYPT) + "/" +
                b(mech.flags & graphene.MechanismFlag.DECRYPT) + "/" +
                b(mech.flags & graphene.MechanismFlag.WRAP) + "/" +
                b(mech.flags & graphene.MechanismFlag.UNWRAP));
        }
    }
}
mod.finalize(); `

It thrwos this error:
`node index.js

/home/marcelo/Documentos/graphene/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
          ^
Error: Dynamic Symbol Retrieval Error: /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so: undefined symbol: C_Initialize
    at DynamicLibrary.get (/home/marcelo/Documentos/graphene/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /home/marcelo/Documentos/graphene/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at Object.Library (/home/marcelo/Documentos/graphene/node_modules/ffi/lib/library.js:47:28)
    at new Pkcs11 (/home/marcelo/Documentos/graphene/node_modules/graphene-pk11/build/pkcs11/pkcs11.js:14:24)
    at Function.Module.load (/home/marcelo/Documentos/graphene/node_modules/graphene-pk11/build/module.js:70:19)
    at Object.<anonymous> (/home/marcelo/Documentos/graphene/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32) `

It would be related with this error: http://stackoverflow.com/questions/22764447/linking-error-with-opensc-pkcs

**Comment by rmhrisk** [comment]
@AndreaFrancis we have a patch that we think resolve your issue, can you confirm. It was fixed in : https://github.com/PeculiarVentures/graphene/issues/38

**Comment by rmhrisk** [comment]
@AndreaFrancis Can you confirm your issue is resolved? We have builds working on Windows here but want to make sure you are OK also.

I am closing this issue given the lack of activity and that we believe this is fixed but we still want to hear back from you.

Ryan
