### ISSUE TITLE
Session C_FindObjectsInit get not PrivateKey Bug!

### ISSUE THREAD

**Issue by erdembas** [PeculiarVentures/graphene#40]
Hi, 
session.find({ class: graphene.ObjectClass.PRIVATE_KEY }) [C_FindObjectsInit] method get not private key object.
Please help me.

**Comment by rmhrisk** [comment]
Can you give sample code and details about your environment?

**Comment by erdembas** [comment]
I am using Windows.10 x64 operation system. 
NodeJs Version : 4.4.5

var lib = "C:/windows/system32/akisp11.dll";
 var graphene = require("graphene-pk11");
 var Module = graphene.Module;

 var mod = Module.load(lib, "akis");

mod.initialize();

var session = mod.getSlots(0).open();
session.login("078066");

// Return 0! PRivate Key object.
console.log(session.find({ class: graphene.ObjectClass.PRIVATE_KEY }).length);

Graphene-pk11 Library 
session.js find method  

`first while loop rv!== pkcs11.CKR_OK enter break; and exit while.`

After objects.push(hObject). rv= this.lib.C_FindObjectsFİnal(this.handle); return 0 object!

Please help me.

**Comment by rmhrisk** [comment]
@erdembas I will try to help.

It seems akisp11.dll is for [uekae](http://uekae.bilgem.tubitak.gov.tr/en/urunler/akis-smart-card-operating-system) based devices/cards.

Do you know this device has been initialized? Do you know if it has any keys on it? Based on the return you are seeing it seems the card has no contents.

If you do not one thing to try is to use [opensc and it's pkcs11-tool](https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer) to inspect the card, this way you can clearly check the contents of the card without taking a circular dependency on Graphene.

Another question becomes can you create keys on the card? One way to check this is to try with the [Graphene CLI](https://unmitigatedrisk.com/?p=541). With it you can [check the performance of the card](https://github.com/PeculiarVentures/graphene/blob/master/DEVICE_CAPABILITIES.md) or simply generate a key:

```
test gen -it 1 -a all
```

The CLI is like pkcs11-tool, if they see something different there is likley a problem with Graphene. 

Please let us know what you find out.

Ryan

**Comment by erdembas** [comment]
SmartCard is initialized and exist any private key on card. I am using java sunpkcs11 provider access private key and create digital signature but using graphene-pk11 not access private key..

**Comment by rmhrisk** [comment]
Can you confirm if the graphene-cli can access the key?

**Comment by microshine** [comment]
It can be a problem with reading structure data from PKCS11 on Windows (https://github.com/TooTallNate/ref-struct/issues/22)

**Comment by rmhrisk** [comment]
Ah, yes I had forgotten about this.

@erdembas can you try on a non-windows machine?

**Comment by rmhrisk** [comment]
Linking https://github.com/PeculiarVentures/graphene/issues/39

**Comment by erdembas** [comment]
SUCCESS.. THE PROBLEM IS FOR WINDOWS.

@rmhrisk I have just tried on Ubuntu 16.04 x32 os and got success. Return two private key result. 
The problem is about windows os. Any idea to solve the problem for windows os.

Thanks

![image](https://cloud.githubusercontent.com/assets/2093046/16738240/87112d7c-479d-11e6-952a-cafd17d8b454.png)

**Comment by rmhrisk** [comment]
@erdembas thanks for doing the check, our issue was either with node-ffi or our use of it, to fix this we ended up re-writing to take out this dependency.

@microshine will do a publication of a new version in the next couple days that should resolve this, we would like to ask that once it is released that you test your token again on Windows.
