### ISSUE TITLE
Uniquely identify generated key[pairs]

### ISSUE THREAD

**Issue by arik-so** [PeculiarVentures/graphene#44]
This isn't really an issue as much as a question, but there aren't any examples for it, so I'll go ahead and ask. What is the best way to uniquely identify a generated keypair? When generating a keypair, it is possible to specify attributes such as e. g. "label," but labels aren't necessarily unique. What is unique is the key index after closing the session, but that is hard to obtain after the session is closed.

When doing `session.find()`, both class and label can be specified, but due to the aforementioned issue of the label not being unique, I was wondering if there is a better way of uniquely obtaining a key property upon generation and then finding it later using that same previously determined property?

**Comment by microshine** [comment]
The CKA_ID field is intended to distinguish among multiple keys. In the case of public and private keys, this field assists in handling multiple keys held by the same subject; the key identifier for a public key and its corresponding private key should be the same. The key identifier should also be the same as for the corresponding certificate, if one exists. Cryptoki does not enforce these associations, however. 

[pkcs11doc](https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__10__7__KEY__OBJECTS.html)

**Comment by arik-so** [comment]
Excellent! How do I obtain the property using Graphene? When getting key attributes of say a public key, there are the fields `modulus` and `publicExponent`. Is `CKA_ID` to be used just like that?

**Comment by rmhrisk** [comment]
Exactly.

You may also be interested in this: https://tools.ietf.org/html/rfc7512

Applications may use this as a scheme to store all associated values in their configuration.

**Comment by arik-so** [comment]
Oddly enough, when I try it, I get the following error: 

> Error: Unsupported attribute name 'CKA_ID'

This is my code:

```
// get public key attributes
var pubKeyAttributes = keys.publicKey.getAttribute({
	modulus: null,
	publicExponent: null,
	CKA_ID: null
});
```

But I should probably be able to figure out it now that I'm on the right track.

**Comment by arik-so** [comment]
Ah, it has worked with a simple `id`. Is that the field I should be using?

**Comment by microshine** [comment]
[Example of setting values](https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/lib/algs/aes.ts#L18)
[Example of searching by key](https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/lib/key_storage.ts#L21)

**Comment by microshine** [comment]
graphene.d.ts must be helpful
[Template interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/graphene-pk11/graphene-pk11.d.ts#L1633)

**Comment by arik-so** [comment]
Excellent! I got it all working, and it's generating unique IDs on key generation that it can also retrieve. Thanks!

**Comment by rmhrisk** [comment]
@arik-so if when you get your self situated we would love a bitcoin sample (which I assume is where you will use graphene).

**Comment by arik-so** [comment]
Absolutely, and thank you very much for your help!

**Comment by rmhrisk** [comment]
Great. FYI we have verified SafeNet does 256k1.

**Comment by rmhrisk** [comment]
@arik-so we would also love to ass whatever device you are testing with to the readme along with the results you see with it in CAPABILITIES.md

**Comment by arik-so** [comment]
Will do! However, I am not yet allowed to talk about the project I'm using it for, sorry :(

**Comment by rmhrisk** [comment]
Of course, wouldn't expect that

**Comment by mechazod** [comment]
Need help for the samples, can you share what you did on generating keypair with `CKA_ID` and then finding it on `session.find()` 

Thank you in-advance.
