### ISSUE TITLE
Use Graphene to update HSM pin and so pin

### ISSUE THREAD

**Issue by arik-so** [PeculiarVentures/graphene#45]
Right now, in order to modify the SoftHSM PIN programmatically in Node, we use the following code:

```javascript
child_process.spawnSync('softhsm2-util', [
    '--module', '/usr/local/lib/softhsm/libsofthsm.so', '--token-label', 'SoftHSM', '-l', '--change-pin', '--new-pin', password
  ], { stdio: 'inherit' });
```

However, for the sake of both code elegance and more easily attained cross-platform-compatibility, I was wondering if it was possible, or whether there are plans to make it possible, to change HSM pins using Graphene, considering all the other HSM interactions that Graphene supports? That would also allow a much easier configuration switch between emulated and hardware HSMs.

**Comment by rmhrisk** [comment]
This is absolutely something we want to support. We will try to find time in the next month to do this but pull requests are welcome too. I don't think it's more than a afternoon of work, it's just a matter of doing the work.

Have you found other operations you want to see added ?

**Comment by arik-so** [comment]
As of right now, it is the only operation I found to be missing. Thank you very much for your support, I'm looking forward to the update!

**Comment by rmhrisk** [comment]
Just created two tracking bugs, one for token initialization and another for changing.

**Comment by arik-so** [comment]
Great, thank you very much!
