### ISSUE TITLE
Implement C_SetPin

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/graphene#46]
It should be possible to set the pin with graphene

**Comment by rmhrisk** [comment]
https://github.com/PeculiarVentures/graphene/blob/master/src/session.ts#L114

Turns out I was wrong and we support this

**Comment by arik-so** [comment]
Ah, indeed, I see it, too. However, are there not two pins that can be set? The regular one, which is in the code, and the SO pin?

**Comment by rmhrisk** [comment]
C_SetPIN modifies the PIN of the user
that is currently logged in, or the CKU_USER PIN if the session is not
logged in.

**Comment by arik-so** [comment]
It modifies pins of a user? I was unaware of any sort of user system at all, I think I have some urgent reading/catching up to do. I thought the pins applied to the whole HSM module.

**Comment by rmhrisk** [comment]
It modifies pins of the logged in user. You can create a session as a user or a security officer.

https://github.com/PeculiarVentures/graphene/blob/master/src/session.ts#L24

You specify at login time: 
https://github.com/PeculiarVentures/graphene/blob/master/src/session.ts#L150

I will write up a HSM 101 document soon.

**Comment by arik-so** [comment]
Ah, oh, the pieces have snapped back into place. I'm not sure what a context-specific user is, but the distinction between user and security officer is very clear. Thank you very much!

**Comment by rmhrisk** [comment]
Think of a slot in PKCS#11 as a virtual HSM. Your session is to a slot. You log in as a user or security officer. The context is the union of that.

**Comment by rmhrisk** [comment]
@arik-so @microshine created unit tests for this case - https://github.com/PeculiarVentures/graphene/issues/48
