### ISSUE TITLE
Debug message of SoftHSM2

### ISSUE THREAD

**Issue by igalco** [PeculiarVentures/graphene#53]
Could it be possible to have the debug message of SoftHSM2 (stderr) (when log.level is set) displayed or returned in the Exception ? thanks !

**Comment by rmhrisk** [comment]
I really don't like the idea of doing anything vendor implementation specific. Graphene is intended to be a vendor neutral middleware for accessing any PKCS#11 devices. Is there not a way to get SoftHSM to log to a log file where you can look at that detail there?

**Comment by igalco** [comment]
That is what I did just now I recompiled softhsm to debug the reason of the error ... So far doesn't tell me how to fix it though

**Comment by rmhrisk** [comment]
Is this maybe helpful https://github.com/Pkcs11Interop/pkcs11-logger

**Comment by igalco** [comment]
Okay i got the answer with the soft hsm team :
https://github.com/opendnssec/SoftHSMv2/issues/245#issuecomment-250452412

I basically need to instantiate this struct 
CK_KEY_DERIVATION_STRING_DATA any idea how to do that with graphene ?

thanks in advance.

Best regards,
-- 
Igal Cohen-Hadria
