### ISSUE TITLE
NPM Install fail

### ISSUE THREAD

**Issue by MckenMakAtThales** [PeculiarVentures/graphene#63]
I am trying to install graphene to CentOS7 and Windows 7 with NodeJS 7.0., the installation "npm install graphene-pk11" will get me the error: " **npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/graphene-pk11/build/console/console.js'**".

I tried install it from the git source, I got the same issue.  Seems like the install script have issue with the NodeJS V7.

[npm-debug.zip](https://github.com/PeculiarVentures/graphene/files/569298/npm-debug.zip)

**Comment by microshine** [comment]
new version of `graphene-pk11` was published. Could you check installation, it works for me

**Comment by MckenMakAtThales** [comment]
Thanks for the quick response!  The new version (2.0.12) works under both NodeJS 6.9.1 and 7.0.0.!!

This only issue is the CLI tool graphene seems not functioning, I tried both with or without file config.json, I get the same message as following:
$ graphene
: No such file or directory

**Comment by microshine** [comment]
Ok, I'll check it soon

**Comment by microshine** [comment]
I changed line from CRLF to LF and republished graphene. Could you check module?
I checked module on Linux it was ok.

**Comment by MckenMakAtThales** [comment]
I is working under CentOS 7!  I will continue trying on other platforms after this weekend.

Thanks!

**Comment by MckenMakAtThales** [comment]
Ubuntu 16 works, but installation fail on  Windows 7.

[npm-debug.zip](https://github.com/PeculiarVentures/graphene/files/575955/npm-debug.zip)

**Comment by microshine** [comment]
It works for me
![image](https://cloud.githubusercontent.com/assets/7333669/20188511/09db8b8e-a78a-11e6-870f-39650d353de9.png)

try to [update](https://docs.npmjs.com/getting-started/installing-node) `npm`

```
npm install npm@latest -g
```

**Comment by MckenMakAtThales** [comment]
Tried again the npm failed, I reinstalled the NodeJS problem still persist.    Just realize, the issue is inside its dependency pkcs11js.

npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! pkcs11js@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkcs11js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by microshine** [comment]
Could you try to build pkcs11js manualy?
```
cd pkcs11js
node-gyp configure build
```

**Comment by MckenMakAtThales** [comment]
I get it from Github then build it, with Python 2.7.10 under Windows 7 . this is what what I got:

C:\temp\pkcs11js> node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.1.0 | win32 | x64
gyp info spawn c:\dev\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py', gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\temp\\pkcs11js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\mmak\\.node-gyp\\7.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\mmak\\.node-gyp\\7.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\temp\\pkcs11js',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\temp\\pkcs11js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:474
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\mmak\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\temp\pkcs11js
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by microshine** [comment]
You have to install `nan` for pkcs11js
```
npm install
```
or
```
npm install nan --save
```

**Comment by MckenMakAtThales** [comment]
Thanks.  I installed it and I still having the following error.  Is my Visual Studio 2012 is part of the problem?

I run the build twice to reduce the output warning and errors, such as the following:
          c:\users\mmak\.node-gyp\7.1.0\include\node\v8.h(1993) : see declaration of 'v8::Value::ToNumber
  '
..\src\pkcs11\param_rsa.cpp(83): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\temp\p
kcs11js\build\pkcs11.vcxproj]
          c:\users\mmak\.node-gyp\7.1.0\include\node\v8.h(1993) : see declaration of 'v8::Value::ToNumber
  '
  param_ecdh.cpp
  pkcs11.cpp
..\src\pkcs11\param_ecdh.cpp(4): warning C4530: C++ exception handler used, but unwind semantics are not
enabled. Specify /EHsc [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\pkcs11\param_ecdh.cpp(24): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\temp\
pkcs11js\build\pkcs11.vcxproj]

-----------------------------------------
Following is the second build 

C:\temp\pkcs11js> node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.1.0 | win32 | x64
gyp info spawn c:\dev\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\temp\\pkcs11js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\mmak\\.node-gyp\\7.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\mmak\\.node-gyp\\7.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\temp\\pkcs11js',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\temp\\pkcs11js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node.cpp
..\src\node.cpp(239): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\temp\pkcs11js\build\pkcs11.vcxproj] ..\src\node.cpp(381): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\temp\pkcs11js\build\pkcs11.vcxproj]
          c:\users\mmak\.node-gyp\7.1.0\include\node\v8.h(1993) : see declaration of 'v8::Value::ToNumber'
..\src\node.cpp(449): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\temp\pkcs11js\build\pkcs11.vcxproj]
          c:\users\mmak\.node-gyp\7.1.0\include\node\v8.h(1993) : see declaration of 'v8::Value::ToNumber'
..\src\node.cpp(512): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\temp\pkcs11js\build\pkcs11.vcxproj]
          c:\users\mmak\.node-gyp\7.1.0\include\node\v8.h(1993) : see declaration of 'v8::Value::ToNumber'
..\src\node.cpp(708): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(774): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(839): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(918): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1013): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1093): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1122): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1148): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1174): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
..\src\node.cpp(1199): error C3861: 'AsyncQueueWorker': identifier not found [C:\temp\pkcs11js\build\pkcs11.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mmak\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mmak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"

gyp ERR! cwd C:\temp\pkcs11js
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by microshine** [comment]
maybe a problem is node version. I've not checked it with node v7. pkcs11js was tested with node v4, v5 and v6 only

**Comment by MckenMakAtThales** [comment]
I compiled under 6.9.1 still have the same issue, I then look into the src\node.js and found that the name scope of AsyncQueueWorker should add Nan::.  I modified the file and had it compile successfully. 

I test it under Windows 7, NodeJS 6.9.1 (VS2013) and 7.1.0 (VS2015), both environment able to complete the build.  Have not perform any functional test yet.  Will try that tomorrow.

I attached the zip file with my changes in the node.cpp.  Please check that out.

[pkcs11js-src-node.zip](https://github.com/PeculiarVentures/graphene/files/584623/pkcs11js-src-node.zip)

**Comment by microshine** [comment]
Ok. Thank you, I'll try it tomorrow.

**Comment by microshine** [comment]
I updated pkcs11js with your code. Could you check it and close issue if it's ok?

**Comment by MckenMakAtThales** [comment]
I tested it now works under both Windows 7 and CentOS 7.
