### ISSUE TITLE
RSA encryption/decryption support

### ISSUE THREAD

**Issue by luiszunigacr** [PeculiarVentures/graphene#67]
Does this library support RSA encryption?
There is an example in the README.md for signing/verifying, but how could I encrypt/decrypt with some RSA mechanism?

**Comment by rmhrisk** [comment]
Yes, take a look at : https://github.com/PeculiarVentures/graphene/blob/master/capabilities/ThalesNShield.md

It shows the graphene-cli using graphene to encrypt also.

The graphene cli may be a good place for you to see how to use the library for encryption.

**Comment by luiszunigacr** [comment]
Thanks, in that page I can see that graphene supports RSA_PKCS encryption (and other RSA mechanisms), but I don't see how to use the library... I mean, would it just be something like this?
```
var alg = {
  name: "CKM_RSA_PKCS"
};
var MESSAGE = "Encrypted message";
var cipher = session.createCipher(alg, keys.publicKey); //keys previously generated
var enc = cipher.update(MESSAGE);
enc = Buffer.concat([enc, cipher.final()]);
```
Or the `alg` object requires another attribute? 
*I have not been able to test this because of an error installing graphene module, but before spending more time trying to install it, I'd like to know if I'll be able to use it.
