### ISSUE TITLE
Importing certificate into a token. Examples.

### ISSUE THREAD

**Issue by Hyperiongit** [PeculiarVentures/graphene#69]
Is this implemented? 
If so, could you please add an example?

**Comment by rmhrisk** [comment]
The right interfaces exist in PKCS11js but we do not have an example doing it, we will add one in the future but would be happy for a PR.

**Comment by microshine** [comment]
https://github.com/PeculiarVentures/graphene#adding-x509-certificate

for X509 I suggest to use [PKIjs](https://www.npmjs.com/package/pkijs) module. This module allows to work with DER encoding certificate.
