### ISSUE TITLE
Failed installation 'TSC' issue

### ISSUE THREAD

**Issue by mechazod** [PeculiarVentures/graphene#71]
![screen shot 2017-02-17 at 10 47 20 am](https://cloud.githubusercontent.com/assets/16739905/23050682/d1c0db74-f4fe-11e6-9b91-4d5ed5e527fb.png)

**Comment by microshine** [comment]
Fixed in v2.0.19

**Comment by mechazod** [comment]
@microshine, thank you it works fine. 👍
