### ISSUE TITLE
Change PIN

### ISSUE THREAD

**Issue by mechazod** [PeculiarVentures/graphene#72]
I tried sample on changing the pin and the response is:
`[TypeError: Parameter 1 MUST be Buffer]`

**Comment by microshine** [comment]
@mechazod Could you send your example of usage. It must work. Here is test for `pkcs11js` lib
https://github.com/PeculiarVentures/pkcs11js/blob/e0f717e34e2d655034f9230515baf01294f9b464/test/test.js#L190-L228

**Comment by mechazod** [comment]
![screen shot 2017-02-20 at 9 48 50 am](https://cloud.githubusercontent.com/assets/16739905/23109195/c51a0ad0-f751-11e6-9625-1d1653d69ec4.png)

**Comment by mechazod** [comment]
Also, I've tried on pkcs11 and it works fine, but on graphene not good. 
It always says
`[TypeError: Parameter 1 MUST be Buffer]`

**Comment by microshine** [comment]
It works for me

```javascript
var graphene = require("graphene-pk11");

var Module = graphene.Module;
var SessionFlag = graphene.SessionFlag;
var UserType = graphene.UserType;

var mod = Module.load("/usr/local/lib/softhsm/libsofthsm2.so", "SoftHSM2");
mod.initialize();

try {
    var slot = mod.getSlots(0);
    var session = slot.open(SessionFlag.SERIAL_SESSION | SessionFlag.RW_SESSION);

    session.login("12345", UserType.User);

    session.setPin("12345", "54321");

    session.logout();

    session.close();

    console.log("Success");
} catch (e) {
    console.error(e);
}

mod.finalize();
```

If I open session without RW flag, I've got error
```
// code
slot.open();

// error
Error: CKR_SESSION_READ_ONLY:181
    at Error (native) C_SetPIN:303
```

**Comment by mechazod** [comment]
@microshine got it, I have now SessionFlag to ReadWrite thats why, thanks again!

**Comment by microshine** [comment]
@mechazod I published `pkcs11js`, there were some spellings errors. I'll publish `graphene` with some updates soon
