### ISSUE TITLE
CKR_FUNCTION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by lukaskiss222** [PeculiarVentures/graphene#73]
I want to use it, to load keys from my card and sign string, but it fails and i get this error:

/home/user/node_modules/graphene-pk11/build/session.js:200
                throw e;

Error: CKR_FUNCTION_NOT_SUPPORTED:84
    at Error (native) C_GenerateKeyPair:901
    at Error (native)
    at Session.generateKeyPair (/home/user/node_modules/graphene-pk11/build/session.js:189:37)
    at Object.<anonymous> (/home/user/Documents/roc/sign_ver.js:16:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

How can I repair this error ?

**Comment by microshine** [comment]
@lukaskiss222 You should use `find` method of `session` to get stored keys from token

Example: Get all private keys from token
```javascript
session.find({class: graphene.ObjectClass.PRIVATE_KEY})
```

If your pkcs#11 library doesn't support `C_GenerateKeyPair`, you should use external tools for it (like [PIV tools](https://www.yubico.com/support/knowledge-base/categories/articles/piv-tools/) for Yubico keys)

**Comment by rmhrisk** [comment]
It's very common for national ID cards and similar devices to not support key generation in their P11 implementations.  These sorts of devices off and expose what called read only card edges  and utilize proprietary provisioning APIs, often based on shared symmetric keys, to generate keys.  I suspect you may be using one such card / device.

**Comment by lukaskiss222** [comment]
Yes I have national ID card and I want to extract from it private key.
Then I want to use it in createSign function and sign text.

I do this
```javascript
var private = session.find({class:graphene.ObjectClass.PRIVATE_KEY})
var sign = session.createSign("RSA_PKCS", private)
```
and I get this error:
TypeError: Parameter 3 MUST be Buffer

My card support this:
Mechanisms:

Name                       h/s/v/e/d/w/u
---------------------------------------------------
SHA_1                      +/-/-/-/-/-/-
SHA224                     +/-/-/-/-/-/-
SHA256                     +/-/-/-/-/-/-
SHA384                     +/-/-/-/-/-/-
SHA512                     +/-/-/-/-/-/-
RSA_PKCS                -/+/+/-/+/-/-

Thanks for help.

**Comment by microshine** [comment]
`find` returns collection of `Object`. You have to select one and use it for `createSign`

```javascript
var privateKeys = session.find({class:graphene.ObjectClass.PRIVATE_KEY});
if (privateKeys.length) {
    var privateKey = privateKeys.items(0); // get 1st key from collection
    var signature = session.createSign("SHA1_RSA_PKCS", privateKey).once(MESSAGE);
    ...
}
```

[example from test](https://github.com/PeculiarVentures/graphene/blob/master/test/rsa.js#L107-L120)

**Comment by lukaskiss222** [comment]
Thank you very much.
That works.
