### ISSUE TITLE
how to certificate data ?

### ISSUE THREAD

**Issue by anlopes123** [PeculiarVentures/graphene#86]
I wonder if it is to capture the data of the certificate as shown in the image below ?
![dadoscertificado](https://user-images.githubusercontent.com/7180022/31817029-3d446126-b571-11e7-8736-b66243cce3ac.png)

**Comment by microshine** [comment]
`graphene` allows to get DER encoded certificate from token. You can use [PKIjs](https://www.npmjs.com/package/pkijs) to parse it and receive the same data you have in dialog box

**Comment by microshine** [comment]
there is one more module [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11). It's based on `graphene` and implements WebCrypto interface. it also uses PKIjs for certificates and requests

[Here](https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/lib/cert.ts) is an example of PKIjs using in `node-webcrypto-p11`
