### ISSUE TITLE
Verify a signature with certificate

### ISSUE THREAD

**Issue by jlardet** [PeculiarVentures/graphene#87]
Hi,

Using given examples in README.md, I generated signatures using my token (SoftHSM2) and would verify them.
I initialized my token outside my Node.js application and did not give it any public key during this process, only a private key and a signed certificate (which should contain public key, if I'm not wrong ?)

I can't find a way to verify with graphene the signature using the certificate in my SoftHSM2 token. Is there a way to handle this case or am I totally wrong about it ?

Should I feed the token with the public key to verify signatures ?

Thanks

**Comment by microshine** [comment]
There is no simple API to verify signature with certificate's public key in graphene. You need to get public key from it and import to your token as session object. You can use [PKIjs](https://github.com/PeculiarVentures/PKI.js) for it.

There is another way to do it. [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11) is module which based on `graphene` and `PKIjs`. It implements WebCrypto API.

```js
const { WebCrypto } = require("node-webcrypto-p11");

const config = {
    library: "/usr/local/lib/softhsm/libsofthsm2.so",
    name: "SoftHSM v2.0",
    slot: 0,
    readWrite: true,
    pin: "12345"
};
const data = new Buffer("You signed data");
const alg = {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"};
const signature = new Buffer("signature"); // :)

const  crypto = new WebCrypto(config);

crypto.certStorage.keys()
  .then((indexes) => {
    // each index has template <type>-<handle>-<hash(spki)>
    // if you need to get private key for certificate, you can find key with the same `<hash(spki)>`
    const certID = indexes[0]; // take you cert
    return crypto.certStorage.getItem(certID, alg, ["verify"]);
  })
  .then((cert) => {
    console.log("Certificate:", cert.subjectName);
    // certificate contains publicKey, you can use it for signature verification
    return crypto.subtle.verify(alg, cert.publicKey, signature, data);
  })
  .then((ok) => {
    console.log("Verification:", ok);
  })
  .catch((err) => {
    console.error(err);
  });
```

**Comment by jlardet** [comment]
Npm module node-webcrypto-p11 matches perfectly my need.
Thanks for your help !
