### ISSUE TITLE
Verifying signature in server-side: Yubikey

### ISSUE THREAD

**Issue by netmiller** [PeculiarVentures/graphene#89]
Maybe totally newbie question, but what tooling I need to verify signature made by Yubikey PIV slot by client-side application.

I can produce signature with Graphene, and my target is to wrap it by Electron-application (nice UI-window, nothing else).

Here is my graphene-code :

````
var graphene = require("graphene-pk11");
var Module = graphene.Module;
var lib = "./lib/libykcs11.dylib";
var mod = Module.load(lib, "test11.js");
var MESSAGE = "Sign this message...please. UID=B94A85F8-9091-4EBF-8813-4B0EE3579EE4.";
mod.initialize();
var slot = mod.getSlots(0);
if (slot.flags & graphene.SlotFlag.TOKEN_PRESENT) {
   const session = slot.open();
   // session.login("123456", graphene.UserType.USER);
   session.login("776655", graphene.UserType.USER);
    var privateKeys = session.find({class:graphene.ObjectClass.PRIVATE_KEY});
    // var publicKeys = session.find({class:graphene.ObjectClass.PUBLIC_KEY});
    if (privateKeys.length) {
        console.log('priv-keys-len='+privateKeys.length);
        const privKey = privateKeys.items(0); // get 1st key from collection
        // var signature = session.createSign("SHA1_RSA_PKCS", privKey).once(MESSAGE);
        // var signature = session.createSign("ECDSA_SHA256", privKey).once(MESSAGE);
        const signature = session.createSign("SHA512_RSA_PKCS", privKey).once(MESSAGE);
        console.log('\+++signature-hex: ',signature.toString('hex'));
    } else  {
    console.log('ei-löydy-slot-0');
    }
}
mod.finalize();
````

and here is results:

````
► iMac@pkcs11$ node test11.js
priv-keys-len=3
+++signature-hex:  138a1dd73a1547a1fa3b18a64dca1612ee1b368fbbe06d6962f039625d297eeed9c11f611bb3c5e347ff56e2efbbd38a17a10125c9625457d306d09cb81f72fc89b152bb630559ce00dd6d2c0cc90c2cfacbdfbc69becfd04f73be8b1e228701477b000f2f3bb86a765b53cfe7f259c194a935bc457170a8e126d8e50be2a77d9fc7f72eb0db28cc3d525fbf234107b009b2fd64c13e82a763e7ab796002a23c553494dbefb56ed5173461ac139ecb604e595d83a6c6e900e934d321f7e52a7aaa8ce81ff677e9d955743d1a447612d45cd0026d4da497b1a9aa713840d22749555121e71a183b11a31ac88b047a0217e78cc27bacc850a1361bf689177cb1ae
````

So, my client-app will fetch MESSAGE from server (via ssh), and return __signature__ (hex or bare) back to server. Plus Yubikey serial number etc. That's already solved. Server-side also have stored client-side __public-keys__  (with serial number/userid/etc).

Now what tools are needed to __verify signature__ .  Is OpenSSL possible to use with this??  Server is quite normal linux-server (dedicated, so I can install what I will).  And what is most reliable and simple way to do it.

Here's also supported mechanisms with Yubikey4 :

````
Slot #0
Slot handle: <Buffer 00 00 00 00 00 00 00 00>
	Description: Yubico Yubikey 4 OTP+U2F+CCID
	Serial: 1234
	Password(min/max): 6/8
	Is hardware: true
	Is removable: false
	Is initialized: true


Mechanisms:
Name                       h/s/v/e/d/w/u
========================================
RSA_PKCS_KEY_PAIR_GEN      -/-/-/-/-/-/-
RSA_PKCS                   -/+/-/-/+/-/-
RSA_PKCS_PSS               -/+/-/-/-/-/-
RSA_X_509                  -/+/-/-/+/-/-
SHA1_RSA_PKCS              -/+/-/-/-/-/-
SHA256_RSA_PKCS            -/+/-/-/-/-/-
SHA384_RSA_PKCS            -/+/-/-/-/-/-
SHA512_RSA_PKCS            -/+/-/-/-/-/-
SHA1_RSA_PKCS_PSS          -/+/-/-/-/-/-
SHA256_RSA_PKCS_PSS        -/+/-/-/-/-/-
SHA384_RSA_PKCS_PSS        -/+/-/-/-/-/-
SHA512_RSA_PKCS_PSS        -/+/-/-/-/-/-
EC_KEY_PAIR_GEN            -/-/-/-/-/-/-
ECDSA                      -/+/-/-/-/-/-
ECDSA_SHA1                 -/+/-/-/-/-/-
ECDSA_SHA256               -/+/-/-/-/-/-
SHA_1                      +/-/-/-/-/-/-
SHA256                     +/-/-/-/-/-/-
SHA384                     +/-/-/-/-/-/-
SHA512                     +/-/-/-/-/-/-
````

All advise are welcome; at least what is the way to go forward with server-side-verifying. Thank's.

**Comment by rmhrisk** [comment]
@netmiller you could use node-webcrypto-ossl in node and do a verify easily. If you wanted the code to be more uniform between client and server you could also use node-webcrypto-p11 on the client side application.

If you want to do verification with the openssl cli you will need to use a signature format like PKCS7/CMS (see PKI.js) as I do not believe raw crypto verify is possible on the command line. You probably want to use a signature format (CMS/XMLDSIG) anyway as it would carry all of the other metadata you want as a verifier.

**Comment by netmiller** [comment]
OK, thanks on advise. I will try to play with __node-webcrypto-p11__ tomorrow. Today we have __Independence Day__ here in Finland, celebrating our first 100 years 💯 . I have lot of questions still, but I'll look what I can achieve, and I hope I can ask more advise, because this is going to be important part of current project. I have spent couple days playing with Yubikey's PGP slot, and have some promising results, but still some problems because I want to make zero-conf-client-app, and think PKCS11 (PIV-slot) will be better bet. Not sure. Anyway, lets see.

**Comment by rmhrisk** [comment]
@netmiller congratulations on your independence day :)

Would love to hear about the larger project, if you can share email at ryan @ peculiarventures dot com.

**Comment by netmiller** [comment]
@rmhrisk  I managed to transfer/verity clientside (Yubikey) signature with serverside __node-webcrypto-ossl__.  Also managed to wrap signature and metadata within simple __json-file__. I haven't yet examined "official" formats like CMS/XMLDSIG; this simple jsonwrapper seems to work in this case.

Wrapper needs also conversions; client-side __arraybuffer-to-string__ (https://github.com/dfcreative/arraybuffer-to-string) and serverside __string-to-arraybuffer__ (https://github.com/dfcreative/string-to-arraybuffer) but this is easy to handle.

Here is my wrapped data :

````
data: {
    "meta": {
        "kassa": "12345",
        "serial": "6946198",
        "dn": "CN=esa.laitila@netmiller.fi, OU=db1,db2,db3, O=vaka.fi",
        "session": "B94A85F8-9091-4EBF-8813-4B0EE3579EE4",
        "ver": "2.3"
    },
    "signature": "Fm7J1ENILEifHa0A8d+7KxkgkJTR9m7+DpkA1NXDApcDGk93GAoP6vbzkPM2/YXPJMM/MPQLFY2cnzo/1XmlW7wUoMMdaGVsy7ECNOZw6AYjNM3kHeNJhtPw6LZFr6/Q5uP/HAaHFdNpH/qYjB0QiVZVTy3k3jI/1bp5+YINabJ/qWbpjJ/093dgqoF3okvtjcfnELMOEKY50EB8+6GEpvT1y4dy1eJjDSnBhhhKrsOPo+M+WMxOtKYIhL2AK5TvfM1sNSY2fp1Ifa5bqgXF3no+SgAeByS0feYaVicrgb1kXlQysTaB7IxCBAgi/ckJ9+nyTNkDBObINDg8kkckMw=="
}
````

Some minor questions/wondering :

* is there any risks with 'arraybuffer-to-str and vice-versa conversions ??
* have not tried __node-webcrypto-p11__ but is there any benefits using it over __graphene__
* node-webcrypto-p11 seems to have some __warnings__ (not to use in production env) ???  
* graphene seems suitable (at a moment) but what do you think (this is going to production within some months) ??
* __node-webcrypto-ossl__ has also similar warnings, but signature verifications seems to work
* is there any special risk with production usage within some months??
* it is quite easy as you said, do I have any better choices??

Thank's for advise.

**Comment by netmiller** [comment]
Didn't mention, but ab2str conversion is made by 'base64'.

````
data.signature = ab2str(signature,'base64');
````

**Comment by rmhrisk** [comment]
Node-webcrypto-pll uses graphene.

Both libraries have the same warning.

We put this on all of our projects. We want teams to make their own suitability decisions. We believe the libraries are of sufficient quality and were designed with security in mind. We also believe third-party assessments are a god thing.

**Comment by netmiller** [comment]
Ok, I think also that quality of libraries are quite sufficient. In future there is also need for encrypt/decrypt, but now signature/verify is what I need. And that seems to work well.

Thank's your advise.  I will return if something arise while doing final codebase  for my app.
