### ISSUE TITLE
Need help on the process on decrypt from encrypt

### ISSUE THREAD

**Issue by mechazod** [PeculiarVentures/graphene#91]
Ex. I run encrypt the text "hello" then I got
Encrypt: 1d4ed857acb7ffb766ed276deb020eda

![screen shot 2017-12-14 at 5 42 07 pm](https://user-images.githubusercontent.com/16739905/33985624-2253afc4-e0f6-11e7-8678-61ae4969cd09.png)

I want to create a code for decrypting the output from encrypt.

**Comment by microshine** [comment]
If you want to encrypt message on one side and decrypt on another you need to share you secret key and encrypt params (algorithm, IV)

### Encryption
```js
const alg = {
    name: "AES_CBC_PAD",
    params: new Buffer("need the same 16"), // must be random value
}

const key = session.create({
    class: graphene.ObjectClass.SECRET_KEY,
    keyType: graphene.KeyType.AES,
    token: false,
    value: new Buffer("12345678901234567890123456789012"), // must be random value
    encrypt: true,          
    decrypt: true,          
})

const data = new Buffer("Hello world")
const enc = session.createCipher(alg, key).once(data, new Buffer((data.length >> 3 << 3) + 16));
console.log(enc); // 69 ee 38 d4 c1 7b 23 ee 14 7b e0 0f 2e 89 73 17
```

### Decryption
```js
const alg = {     
    name: "AES_CBC_PAD",
    params: new Buffer("need the same 16"), // must be the same like for encryption
}

const key = session.create({
    class: graphene.ObjectClass.SECRET_KEY,
    keyType: graphene.KeyType.AES,
    token: false,
    value: new Buffer("12345678901234567890123456789012"), // must be the same like for encryption
    encrypt: true,          
    decrypt: true,          
})
    
    const enc = new Buffer("69ee38d4c17b23ee147be00f2e897317", "hex");
    const dec = session.createDecipher(alg, key).once(enc, new Buffer(enc.byteLength));
    console.log(dec.toString()); // Hello world
```

**Comment by microshine** [comment]
I use SoftHSMv2 for test. It works for script I sent before

`CKR_GENERAL_ERROR:5` is native error from PKCS#11 module.
it can be 
- specific PKCS#11 implementation
- wrong data for decryption

@mechazod  could you share code which you are running?

**Comment by mechazod** [comment]
https://gist.github.com/mechazod/630292945c73e679a3fd72d264cdb1fb

**Comment by mechazod** [comment]
@microshine Got the procedure to find the object. Thanks it works now. 👍
