### ISSUE TITLE
ECDSA-Sign Problem - Where do I get s and r?

### ISSUE THREAD

**Issue by Mik13** [PeculiarVentures/graphene#96]
I'm usign following code to sign a buffer with ECDSA:
```javascript
const sign = session.createSign("ECDSA", privKey.toType(graphene.ObjectClass.PRIVATE_KEY));
sign.update(buffer);
console.log("Signature:", sign.final().toString('hex'));
```

The ECDSA Key used is a secp256k1, and the resulting signature is a 64byte buffer. This does not look like an ASN Sequence, because it does not start with 0x30, and is different every time run. So this looks like the s value, but the r value is missing. Where do I get that from?

Thanks in advance!

**Comment by microshine** [comment]
Signature is concatenated `r` and `s`. You can split it by 32 bytes
Here is source code how I do it for ECDSA signature in `node-webcrypto-ossl` module
https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/src/ec/ec_dsa.cpp#L71
