### ISSUE TITLE
help: It is possible to run a graphene example on Browsers like a normal javascripts file ?

### ISSUE THREAD

**Issue by ELARCHA** [PeculiarVentures/graphene#98]
Thanks you in advance, just I want to use graphene on my browser (client side not server side) and use it in my html file.

**Comment by microshine** [comment]
[Fortify](https://fortifyapp.com/) allows to used PKCS#11 in browser. It uses `graphene-pk11` and implements WebCrypto API

[Here](https://github.com/PeculiarVentures/fortify-examples) are examples of Fortify using from browser

**Comment by ELARCHA** [comment]
Thanks, just i want to detect if a user inject a smart card  token  to logout it to my  web application.

**Comment by microshine** [comment]
Fortify has API to listen token insertion/removing

```js
ws.cardReader
  .on("insert", (info) => {
    console.log("Token was added");
  })
  .on("remove", (info) => {
    console.log("Token was removed");
  })
  .on("error", (error) => {
    console.error(error);
  })
```

**Comment by ELARCHA** [comment]
Thanks i don't find it in the examples of Fortify how can i implements this  i just add and i can detect the smart card. and i don't need to add other lib.

**Comment by microshine** [comment]
`graphene` is NodeJS module. It uses native plugin for PKCS#11 usage. It can not be in browser

**Comment by rmhrisk** [comment]
@ELARCHA you mean the fortify challenge?

No you can not by pass that.

**Comment by ELARCHA** [comment]
thank you for your response, how can force it to push me to enter the pin of the card every time i want to use a certificate to sign ?

**Comment by microshine** [comment]
WebCryptoSocket which you use like Fortify client from browser allows to login and logout PKCS#11 session. You need to login before signing operation, then you can call `logout` method to close PKCS#11 session

https://github.com/PeculiarVentures/webcrypto-local/blob/master/src/socket/crypto.ts#L32-L59

you can play with it in https://peculiarventures.github.io/fortify-examples/example4.html

![image](https://user-images.githubusercontent.com/7333669/45498247-59801d80-b782-11e8-998f-71db39953eda.png)

```js
async function restart() {
  var wcrypto = await ws.getCrypto("981891ae7c940d3b01b47f998d084cc03a48589c");
  if (await wcrypto.isLoggedIn()){
    await wcrypto.logout()
  }

  // do something
  // ...

  await wcrypto.login()
}
```

**Comment by rmhrisk** [comment]
Pin entry is a function of card policy and/or session management. If you want a pin for each operation it is really only security theater unless the card is enforcing this.

**Comment by rmhrisk** [comment]
In the future please use the fortify repository for issues relating to fortify.
