### ISSUE TITLE
Save existing rsa key pair

### ISSUE THREAD

**Issue by olandreievvirtru** [PeculiarVentures/graphene#99]
I try to save existing RSA public/private key with following code:
```javascript 
       const pubKey =  readFilSync("...rsa.pub");
        session.create({
            class: graphene.ObjectClass.PUBLIC_KEY,
            keyType: graphene.KeyType.RSA,
            encrypt: true,
            decrypt: true,
            token: true,
            value: pubKey,
            label: "RSA key",
        });
```
and recive this Error
> Error: CKR_ATTRIBUTE_TYPE_INVALID:18
>     at Error (native) C_CreateObject:489
>     at Session.create (.../node_modules/graphene-pk11/build/session.js:61:32)
>     at ImportCommand.onRun (.../import.ts:17:17)

What format of key do I need to use? 
Maybe I need previously convert key data?

**Comment by microshine** [comment]
Do you know module [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11)?
This module allows to import keys in DER format

You use wrong template for RSA public key. You must set required properties like `publicExponent` and `modulus`. You need to parse public key blob by ASN1 parser and extract these values
Here is source code from node-webcrypto-p11 for RSA public key creating from data
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/lib/crypto/rsa.ts#L248-L256

**Comment by olandreievvirtru** [comment]
@microshine thanks very much
